services: 
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@55w0rd
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./apps/api/db/init.sql:/docker-entrypoint-initdb.d/init.sql
  api:
    build: ./apps/api/
    environment:
      - JWT_SECRET=mysupersecretkey
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=p@55w0rd
      - DB_NAME=postgres
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  pgdata:
